import sqlite3
import pandas as pd
from datetime import datetime
import os
import argparse

class BioCrawlerMeddashBridge:
    def __init__(self, biocrawler_db_path=r"C:\Users\email\.gemini\antigravity\Meddash_organized_backend\06_Shared_Datastores\biocrawler_leads.db", meddash_db_path=r"C:\Users\email\.gemini\antigravity\Meddash_organized_backend\06_Shared_Datastores\meddash_kols.db"):
        self.biocrawler_db = biocrawler_db_path
        self.meddash_db = meddash_db_path
        self.output_dir = "outreach_campaigns"
        
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def fetch_new_tier_a_leads(self):
        """Step 1: Get all Tier A leads generated by BioCrawler today."""
        print(f"[{datetime.now().strftime('%H:%M:%S')}] Querying BioCrawler for new Tier A targets...")
        try:
            with sqlite3.connect(self.biocrawler_db) as conn:
                # In a real scenario, you'd filter by `date_added >= DATE('now')`
                # For this demo, we'll grab a few mock leads generated by our tests
                query = """
                    SELECT company_name, primary_indication, trial_nct_id 
                    FROM biotech_leads 
                    WHERE tier = 'A' OR recent_funding_signal = 1
                    LIMIT 3
                """
                leads = pd.read_sql_query(query, conn)
                
            if leads.empty:
                print("No new Tier A leads found today. Sleeping...")
                return []
                
            print(f"Found {len(leads)} high-priority targets ready for outreach.")
            return leads.to_dict('records')
            
        except Exception as e:
            print(f"Error connecting to BioCrawler DB: {e}")
            return []

    def score_kols_for_indication(self, indication):
        """
        Step 2: Connect to Meddash and run the proprietary SVS math.
        (This mimics the core Meddash 'run_pipeline.py' logic for the specific disease).
        """
        try:
            # We must connect to the core Meddash database here.
            # (Assuming standard schema based on the Meddash architecture we've discussed).
            with sqlite3.connect(self.meddash_db) as conn:
                
                # We simulate the SVS math query here. In production, this would call
                # the Meddash SVS Pandas logic directly. We look for KOLs tagged with
                # the target indication (or MeSH child term).
                query = f"""
                    SELECT 
                        k.first_name, k.last_name, k.institution, 
                        (pm.is_major_topic * 5 + 10) AS simulated_svs_score
                    FROM associated_kols k
                    -- Mocking the join to the publications map based on indication
                    LIMIT 3
                """
                # For this MVP implementation script before Meddash is fully populated, 
                # we'll return a static list of "Rising Stars" to test the handoff format.
                
                print(f"  -> Running Meddash SVS scoring on indication: {indication}")
                mock_rising_stars = [
                    {"name": "Dr. Sarah Chen", "institution": "Dana-Farber", "svs_score": 88.5},
                    {"name": "Dr. Marcus Vance", "institution": "MD Anderson", "svs_score": 82.1},
                    {"name": "Dr. Elena Rostova", "institution": "Memorial Sloan Kettering", "svs_score": 79.4}
                ]
                return mock_rising_stars
                
        except Exception as e:
             print(f"Error running Meddash SVS Pipeline: {e}")
             return []

    def generate_outreach_templates(self, leads):
        """Step 3: Generate the 'Feasibility Rescue' wedge template directly to file."""
        if not leads: return
        
        print(f"\n[{datetime.now().strftime('%H:%M:%S')}] Generating AI SDR Outreach Templates...")
        
        for lead in leads:
            company = lead['company_name']
            indication = lead['primary_indication']
            nct_id = lead['trial_nct_id']
            
            # 1. Score the KOLs
            top_kols = self.score_kols_for_indication(indication)
            
            # 2. Format the template
            filename = f"{self.output_dir}/SDR_Teaser_{company.replace(' ', '')}.txt"
            
            template = f"""
=========================================================
Subject: Rising Star Feasibility data for {indication} trial ({nct_id})
To: CMO @ {company}
=========================================================

Hi [CMO First Name],

Noticed {company} is scaling its clinical operations team for your upcoming {indication} trial. 

Most legacy KOL maps focus on 'Established' researchers who are already over-committed. Our proprietary Scientific Velocity Score (SVS) algorithm recently identified a localized network of "Rising Star" investigators specifically within the {indication} footprint whose publication output has accelerated rapidly over the last 12 months.

As a quick teaser, here are 3 investigators in that cohort:
1. {top_kols[0]['name']} ({top_kols[0]['institution']}) - SVS Velocity: {top_kols[0]['svs_score']}
2. {top_kols[1]['name']} ({top_kols[1]['institution']}) - SVS Velocity: {top_kols[1]['svs_score']}
3. {top_kols[2]['name']} ({top_kols[2]['institution']}) - SVS Velocity: {top_kols[2]['svs_score']}

Would a complimentary 3-page feasibility sample of this cohort be useful for your team as you plan site selection?

Best,
[Your Name]
Meddash Intelligence
"""
            with open(filename, 'w') as f:
                f.write(template.strip())
                
            print(f"  [Success] Saved ready-to-send template for {company} to '{filename}'")

    def run_bridge(self):
        """Execute the full autonomous loop."""
        print("==================================================")
        print("MEDDASH AUTOMATION BRIDGE: BioCrawler -> SVS Engine")
        print("==================================================\n")
        
        leads = self.fetch_new_tier_a_leads()
        self.generate_outreach_templates(leads)
        
        print(f"\n[{datetime.now().strftime('%H:%M:%S')}] Bridge execution complete. Zero-Touch Workflow resting.")

if __name__ == "__main__":
    bridge = BioCrawlerMeddashBridge()
    bridge.run_bridge()
