import pandas as pd
from datetime import datetime

data = [
    {"Script Identifier (Alias)": "P1", "Python Script Name": "run_pipeline.py", "Active Workspace": "01_KOL_Data_Engine", "Function Description": "Main orchestration script for nightly KOL ingestion and scoring.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "P2", "Python Script Name": "extract_publications.py", "Active Workspace": "01_KOL_Data_Engine", "Function Description": "Pulls pubmed literature and ORCID mapping natively via NCBI.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "P3", "Python Script Name": "db_ingestion.py", "Active Workspace": "01_KOL_Data_Engine", "Function Description": "Upserts global publications, authors, and universities into PostgreSQL.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "P4", "Python Script Name": "kol_disambiguator.py", "Active Workspace": "01_KOL_Data_Engine", "Function Description": "Performs 4-signal heuristic scoring to identify duplicate authors.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "P5", "Python Script Name": "kol_weight.py", "Active Workspace": "01_KOL_Data_Engine", "Function Description": "Calculates the final Scientific Value Score (SVS) using journal SJR values.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "P6", "Python Script Name": "load_sjr.py", "Active Workspace": "01_KOL_Data_Engine", "Function Description": "One-time ingestion of Scimago Journal Ranks into the database.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "HumanLLM", "Python Script Name": "review_disambiguations.py", "Active Workspace": "01_KOL_Data_Engine", "Function Description": "Terminal interface hooking into Gemini to manually review merge tickets.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    
    {"Script Identifier (Alias)": "CT1", "Python Script Name": "ct_crawler.py", "Active Workspace": "02_CT_Data_Engine", "Function Description": "Advanced web crawler mapping ClinicalTrials.gov API v2.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "CT2", "Python Script Name": "ct_ingestion.py", "Active Workspace": "02_CT_Data_Engine", "Function Description": "Parses raw CT JSON structures into the strict 11-table relational database graph.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "CT3", "Python Script Name": "ct_mesh_mapper.py", "Active Workspace": "02_CT_Data_Engine", "Function Description": "Strictly maps raw raw trial strings to controlled MeSH headers for universal routing.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "CT4", "Python Script Name": "ct_kol_bridge.py", "Active Workspace": "02_CT_Data_Engine", "Function Description": "Bridges clinical trial principal investigators natively to established core KOL nodes.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "CT5", "Python Script Name": "ct_results_parser.py", "Active Workspace": "02_CT_Data_Engine", "Function Description": "Parses Trial Outcomes and Adverse Event (AE) structural tables natively.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "CT6", "Python Script Name": "ct_pub_bridge.py", "Active Workspace": "02_CT_Data_Engine", "Function Description": "Bridges literature PMIDs referenced natively inside Clinical Trials into the KOL graph.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "CT7", "Python Script Name": "ct_eligibility_parser.py", "Active Workspace": "02_CT_Data_Engine", "Function Description": "Parses strict inclusion/exclusion criteria, biomarkers, and cancer staging parameters.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "Brief", "Python Script Name": "generate_kol_brief.py", "Active Workspace": "04_Product_KOL_Briefs", "Function Description": "Generates the final comprehensive multi-page KOL PDF brief outputs merging CT and Publication domains.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    
    {"Script Identifier (Alias)": "B1 / B2", "Python Script Name": "biocrawler.py", "Active Workspace": "03_BioCrawler_GTM", "Function Description": "Autonomous bot identifying high-signal early Biotech/Pharma startup leads.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "Bridge", "Python Script Name": "bridge_engine.py", "Active Workspace": "03_BioCrawler_GTM", "Function Description": "The synaptic bridging layer evaluating native SVS scores across BioCrawler startup datasets.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    
    {"Script Identifier (Alias)": "CRM1", "Python Script Name": "push_to_sheets.py", "Active Workspace": "03_BioCrawler_GTM", "Function Description": "Pushes Top 20 daily validated leads securely into the active Google Sheet CRM table.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "CRM2", "Python Script Name": "pull_from_sheets.py", "Active Workspace": "03_BioCrawler_GTM", "Function Description": "Securely reverse-syncs manual overrides (e.g. Website URLs) from Google Sheets natively back into PostgreSQL.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    
    {"Script Identifier (Alias)": "TA1", "Python Script Name": "fetch_ta_landscape_data.py", "Active Workspace": "05_Product_TA_Landscape", "Function Description": "Extracts highly consolidated aggregate metrics across the entire KOL and Trial datastore for high-level insight mapping.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    {"Script Identifier (Alias)": "TA2", "Python Script Name": "generate_ta_landscape_stepwise.py", "Active Workspace": "05_Product_TA_Landscape", "Function Description": "Performs Human-in-the-Loop multi-prompt LLM sequence interactions to strictly draft final Therpeuric Area Lanscape PDFs.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    
    {"Script Identifier (Alias)": "Ont1", "Python Script Name": "build_disease_ontology.py", "Active Workspace": "08_MDM_Ontology_Engine", "Function Description": "Securely ingests NIH/CDC native databases continuously to maintain constant MeSH/ICD10/SNOMED Master Data graph alignment.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"},
    
    {"Script Identifier (Alias)": "API", "Python Script Name": "api_server.py", "Active Workspace": "Root / Sidecar", "Function Description": "Crucial FastAPI bridging layer unlocking secure HTTP subprocess routing from Next.js natively into executing Python infrastructure.", "Last Updated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "Update Reason": "Initial Documentation Audit (Version 2.0)"}
]

df = pd.DataFrame(data)
df.to_excel("C:/Users/email/.gemini/antigravity/CTO/MEDDASH_BACKEND_WORKFLOW/meddash backend workflow ver 2.0/meddash_scripts_dictionary.xlsx", index=False)
print("Dictionary Excel Build Success")
